### ISSUE TITLE
Potential security issue in src/cbstring/bstrlib.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/HLSLcc#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

2 instances of this defect were found in the following locations:
---
**Instance 1**
File : `src/cbstring/bstrlib.c` 
Function: `buildCharField` 
https://github.com/sagpant/HLSLcc/blob/45cd5126a8e95bbf755f6c68af9f9befb97ded5b/src/cbstring/bstrlib.c#L2555
Code extract:

```cpp
    }
    else
    {
        buildCharField(&chrs, splitStr); <------ HERE
        ret = p = i = 0;
        for (;;)
```

**How can I fix it?** 
Correct reference usage found in `src/cbstring/bstrlib.c` at line `2261`.
https://github.com/sagpant/HLSLcc/blob/45cd5126a8e95bbf755f6c68af9f9befb97ded5b/src/cbstring/bstrlib.c#L2261
Code extract:

```cpp
        term->data == NULL || r->mlen <= 0 || r->slen < 0 ||
        r->mlen < r->slen) return BSTR_ERR;
    if (term->slen == 1) return bsreadlna(r, s, term->data[0]);
    if (term->slen < 1 || buildCharField(&cf, term)) return BSTR_ERR; <------ HERE

    l = s->buff->slen;
```

---
**Instance 2**
File : `src/cbstring/bstrlib.c` 
Function: `buildCharField` 
https://github.com/sagpant/HLSLcc/blob/45cd5126a8e95bbf755f6c68af9f9befb97ded5b/src/cbstring/bstrlib.c#L2832
Code extract:

```cpp
    if (splitStr->slen == 1)
        return bsplitcb(str, splitStr->data[0], pos, cb, parm);

    buildCharField(&chrs, splitStr); <------ HERE

    p = pos;
```

**How can I fix it?** 
Correct reference usage found in `src/cbstring/bstrlib.c` at line `2261`.
https://github.com/sagpant/HLSLcc/blob/45cd5126a8e95bbf755f6c68af9f9befb97ded5b/src/cbstring/bstrlib.c#L2261
Code extract:

```cpp
        term->data == NULL || r->mlen <= 0 || r->slen < 0 ||
        r->mlen < r->slen) return BSTR_ERR;
    if (term->slen == 1) return bsreadlna(r, s, term->data[0]);
    if (term->slen < 1 || buildCharField(&cf, term)) return BSTR_ERR; <------ HERE

    l = s->buff->slen;
```

**Comment by siva-msft** [comment]
lgtm. all other occurrences are checked for
